version: '3.3'

networks:
  network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    restart: always
    networks:
      - network
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: treeblog
      MYSQL_USER: treeblog
      MYSQL_PASSWORD: treeblog
      MYSQL_DATABASE: treeblog
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: treeblog:latest
    networks:

      - network
    volumes:
      - app_data:/var/www/html/storage/app/public
    env_file: ./.env
    depends_on:
      - mysql

  nginx-tls:
    build:
      context: .
      dockerfile: Dockerfile-nginx-tls
    image: nginx:latest
    restart: always
    container_name: nginx_tls
    volumes:
      - app_data:/var/www/html/public/storage
      - ./deploy/nginx/etc/ssl:/etc/nginx/ssl
    ports:
        - "443:443"
    environment:
        - TZ=America/Chicago
        - LETSENCRYPT=true
        - LE_EMAIL=qouiqaismael890@gmail.com
        - LE_FQDN=www.ismaelqouiqa.com
        #- SSL_CERT=le-crt.pem
        #- SSL_KEY=le-key.pem
        #- SSL_CHAIN_CERT=le-chain-crt.pem
    networks:
      - network
    links:
      - app
volumes:
  app_data:
    driver: local
