FROM nginx:stable-alpine

ADD ./deploy/nginx/conf/nginx.conf /etc/nginx/nginx.conf
ADD ./deploy/nginx/conf/service.conf /etc/nginx/conf.d/service.conf

ADD ./deploy/nginx/script/entrypoint.sh /entrypoint.sh
ADD ./deploy/nginx/script/le.sh /le.sh
ADD ./public /var/www/html/public

RUN \
 rm /etc/nginx/conf.d/default.conf && \
 chmod +x /entrypoint.sh && \
 chmod +x /le.sh && \
 apk add  --update certbot tzdata openssl && \
 rm -rf /var/cache/apk/*

CMD ["/entrypoint.sh"]