version: '3.3'

networks:
  network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    restart: always
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: treeblog
      MYSQL_USER: treeblog
      MYSQL_PASSWORD: treeblog
      MYSQL_DATABASE: treeblog
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: treeblog:latest
    networks:

      - network
    volumes:
      - app_data:/var/www/html/storage/app/public
    env_file: ./.env
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - app_data:/var/www/html/public/storage
      - /etc/nginx/ssl/live/ismaelqouiqa.com/privkey.pem:/etc/nginx/ssl/live/ismaelqouiqa.com/privkey.pem
      - /etc/nginx/ssl/live/ismaelqouiqa.com/fullchain.pem:/etc/nginx/ssl/live/ismaelqouiqa.com/fullchain.pem
    ports:
      - "81:81"
    networks:
      - network
    links:
      - app

volumes:
  app_data:
    driver: local
