version: '3.3'

networks:
  network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    restart: always
    networks:
      - network
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: treeblog
      MYSQL_USER: treeblog
      MYSQL_PASSWORD: treeblog
      MYSQL_DATABASE: treeblog
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: treeblog:latest
    networks:

      - network
    volumes:
      - app_data:/var/www/html/storage/app/public
    env_file: ./.env
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - app_data:/var/www/html/public/storage
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - shared-volume:/etc/nginx/ssl/:ro
    ports:
        - "80:80"
        - "443:443"
    networks:
      - network
    links:
      - app
  ping:
    image: busybox
    command: touch /etc/letsencrypt/testcertificat
    volumes:
      - shared-volume:/etc/letsencrypt/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/


  #certbot:
   # image: certbot/certbot:latest
    #volumes:
  #    - ./certbot/www/:/var/www/certbot/:rw
     # - shared-volume:/etc/letsencrypt/:rw
volumes:
  app_data:
    driver: local
  shared-volume: